### PR TITLE
Fix various issues with templates and variables

### LINKED ISSUE #93: entities parameter does not accept variable
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** Master Branch
**Last working release (if known):** unknown
**Browser and Operating System:** chrome 96.0.4664.110, Win 11

**Description of problem:**

entity list based of variables is not working for me.
For example:
```
type: custom:config-template-card
variables:
  STATE_KEYS: Object.keys(states).filter(k => k.startsWith('sensor'))
entities: ${STATE_KEYS}
```
or
```
type: custom:config-template-card
variables:
  STATE_KEYS: Object.keys(states).filter(k => k.startsWith('sensor'))
entities: 
  - ${STATE_KEYS}
```

**Additional information:**

This seems to be an error with the shouldUpdate function, as the evaluation of the Variables is carried out too late.
I've made the following change locally, which solves the problem for me:

old:
```
 if (oldHass) {
    for (const entity of this._config.entities) {
      const evaluatedTemplate = this._evaluateTemplate(entity);
      if (Boolean(this.hass && oldHass.states[evaluatedTemplate] !== this.hass.states[evaluatedTemplate])) {
        return true;
      }
    }
    return false;
  }
```
new:
```
if (oldHass) {
    for (const entity of this._evaluateTemplate(this._config.entities)) {
        if (Boolean(this.hass && oldHass.states[entity] !== this.hass.states[entity])) {
            return true;
        }
    }
    return false;
}
```

### PR DESCRIPTION
**Pull request by PaulSD**
See the individual commit messages for details.

Fixes #93, Closes #110, Closes #119, Closes #123, Closes #128, Closes #129, Closes #135, Closes #147, Closes #148
(This includes/supersedes #110, #128, #129, #135, and #148, and eliminates the need for #119, #123, and #147)

### CODE REVIEW

**Comment by PaulSD** [comment]
@ildar170975
Anything you can do to help move this along?

**Comment by ildar170975** [comment]
Hi Paul.
Please give me some time for this. I saw your PRs but not analysed them yet.

**Comment by PaulSD** [comment]
(I merged #148 here, since it is necessary to fix the build issues.)

**Comment by iamdabe** [comment]
This looks great! currently running this pr with no issues.

File: src/config-template-card.ts [hunk 1]
```diff
@@ -171,57 +169,37 @@ export class ConfigTemplateCard extends LitElement {
...
+        config[i] = this._evaluateConfig(value);
       }
+    } else if (typeof config === 'object') {
+      Object.entries(config).forEach(entry => {
+        const key = entry[0];
+        const value = entry[1];
+        config[key] = this._evaluateConfig(value);
+      });
+    } else if (typeof config === 'string' && config.includes('${')) {
+      return _evaluateTemplate(config);
```
Comment (oddlama) [inline src/config-template-card.ts]: did you mean `this._evaluateTemplate`? I'm getting a compile error here.

File: src/config-template-card.ts [hunk 2]
```diff
@@ -249,10 +227,19 @@ export class ConfigTemplateCard extends LitElement {
...
     }
 
-    return eval(varDef + template.substring(2, template.length - 1));
+    if (template.startsWith("${") && template.endsWith("}")) {
+      // The entire property is a template, return eval's result directly
+      // to preserve types other than string (eg. numbers)
+      return eval(template.substring(2, template.length - 1));
+    }
+
+    template.match(/\${[^}]+}/g).forEach(m => {
```
Comment (oddlama) [inline src/config-template-card.ts]: the match may be `null` giving another compile error. can we maybe do this?
```
const matches = template.match(/\${[^}]+}/g);
if (matches) {
  matches.forEach(m => {
    const repl = eval(m.substring(2, m.length - 1));
    template = template.replace(m, repl);
  });
}
```

**Comment by gieljnssns** [comment]
> This looks great! currently running this pr with no issues.

How do you run this PR?

File: src/config-template-card.ts (hunk 1 above)
Comment (PaulSD) [reply src/config-template-card.ts]: Good catch.  Thanks!

**Comment by PaulSD** [comment]
> How do you run this PR?

I haven't tested this with HACS, but I think adding https://github.com/PaulSD/config-template-card to HACS as a custom repo should work.

Or you can download https://github.com/PaulSD/config-template-card/releases/download/1.3.6.1/config-template-card.js, manually overwrite the original copy in HA in `/config/www/community/config-template-card/config-template-card.js`, either update or remove `/config/www/community/config-template-card/config-template-card.js.gz`, then clear your browser cache.

**Comment by PaulSD** [comment]
Ping @ildar170975

**Comment by ildar170975** [comment]
@PaulSD 
Hi Paul. Sorry for being unavailable. Was very busy... Let's merge it & test together!

**Comment by ildar170975** [comment]
Merged this to `dev` (just cloned a `base` branch). Let's make a pre-release.

**Comment by ildar170975** [comment]
@PaulSD 
Please check https://github.com/iantrich/config-template-card/issues/166
